// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncMesh.EventStore;

#nullable disable

namespace SyncMesh.EventStore.Migrations.Postgres.Migrations
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20260722183723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncMesh.EventStore.EventRecord", b =>
                {
                    b.Property<Guid>("GlobalEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("HlcLogicalCounter")
                        .HasColumnType("integer");

                    b.Property<long>("HlcPhysicalTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginSiteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PayloadSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("bigint");

                    b.HasKey("GlobalEventId");

                    b.HasIndex("HlcPhysicalTicks", "HlcLogicalCounter");

                    b.HasIndex("StreamId", "StreamVersion")
                        .IsUnique();

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
