// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncMesh.EventStore;

#nullable disable

namespace SyncMesh.EventStore.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20260722183715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SyncMesh.EventStore.EventRecord", b =>
                {
                    b.Property<Guid>("GlobalEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("HlcLogicalCounter")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HlcPhysicalTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginSiteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PayloadSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("GlobalEventId");

                    b.HasIndex("HlcPhysicalTicks", "HlcLogicalCounter");

                    b.HasIndex("StreamId", "StreamVersion")
                        .IsUnique();

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
